export const contactPage = `<section class="wrap contact-section">
<div class="contact-heading"><p class="eyebrow">Residential &amp; commercial · Central Texas</p><h1>Let’s talk about<br>your project.</h1><p>Tell us a little about what you’re planning. Whether you’re ready to build or just exploring options, we’d love to hear from you.</p></div>
<div class="contact-layout"><aside class="contact-details" aria-label="Contact options"><h2 class="eyebrow">Prefer to talk?</h2><a class="contact-phone" href="tel:+17373009848" aria-label="Call Verde at 737-300-9848">737-300-9848</a><div class="contact-method"><span>Email us directly</span><a href="mailto:hello&#64;verdelandscapes&#46;com">hello&#64;verdelandscapes&#46;com</a></div><div class="contact-commercial"><h3>Commercial project or bid request?</h3><p>Use the same short form below, or email plans and bid documents directly to our team. We can gather the full scope when we connect.</p></div></aside>
<div class="inquiry-panel"><h2>Start with a quick introduction.</h2><p class="form-intro">Just three required fields. We’ll take it from there.</p>
<form action="https://formsubmit.co/hello&#64;verdelandscapes&#46;com" method="POST" class="inquiry-form">
<input type="hidden" name="_subject" value="New Verde website project inquiry"><input type="hidden" name="_template" value="table"><input type="text" name="_honey" style="display:none" tabindex="-1" autocomplete="off" aria-hidden="true">
<label>Your name *<input name="Name" autocomplete="name" required maxlength="120" placeholder="First and last name"></label>
<div class="form-pair"><label>Email *<input type="email" name="email" autocomplete="email" required maxlength="254" placeholder="you@example.com"></label><label>Phone *<input type="tel" name="Phone" autocomplete="tel" required maxlength="40" placeholder="(512) 555-0123"></label></div>
<label>Project type <span>(optional)</span><select name="Project type"><option value="">What are you planning?</option><option>Residential landscape or hardscape</option><option>Commercial landscape or hardscape</option><option>Ranch / other property</option><option>Not sure yet</option></select></label>
<label>Project city or area <span>(optional)</span><input name="Project location" autocomplete="address-level2" maxlength="120" placeholder="e.g. Austin, Lakeway, San Antonio"></label>
<label>A little about your project <span>(optional)</span><textarea name="Project details" rows="4" maxlength="5000" placeholder="What would you like to build or improve? A sentence or two is plenty."></textarea></label>
<p class="form-note">By submitting, you’re asking Verde to contact you about your inquiry. FormSubmit processes the form to deliver your message to our team.</p>
<button class="button" type="submit">Let’s discuss your project <span aria-hidden="true">↗</span></button>
</form></div></div></section>`;
