import {serviceDetails} from '../content/services.mjs';
import {localGuides} from '../content/local-services.mjs';
import {slug,projects} from '../content/site.mjs';

export async function renderServices(page, esc, button) {
  const list = items => `<ul>${items.map(s=>`<li>${esc(s)}</li>`).join('')}</ul>`;
  const links = names => `<ul>${names.map(n=>`<li><a href="/services/${slug(n)}/">${esc(n)}</a></li>`).join('')}</ul>`;
  for (const s of serviceDetails) {
    await page(`/services/${slug(s.name)}/`,`${s.name} in Central Texas`,s.description,`<section class="wrap section service-page"><p class="breadcrumb"><a href="/services/">Services</a> / ${esc(s.name)}</p><p class="eyebrow">Residential & commercial · Central Texas</p><h1>${esc(s.name)} in Central Texas.</h1><p class="service-tagline">${esc(s.headline)}</p><p>${esc(s.intro)}</p>${button('/contact/','Discuss your project')}<div class="section split"><div><h2>Define the scope.</h2>${list(s.scope)}</div><div><h2>Plan the work.</h2><p>${esc(s.planning)}</p></div></div><div class="split"><article><h2>Residential properties.</h2><p>${esc(s.residential)}</p></article><article><h2>Commercial properties.</h2><p>${esc(s.commercial)}</p></article></div>${s.project?`<p class="project-reference">See this work in practice: <a href="/case-studies/${s.project}/">${esc(projects.find(p=>p.slug===s.project).name)}</a>.</p>`:''}<h2>Common questions.</h2>${s.faqs.map(([q,a])=>`<details><summary>${esc(q)}</summary><p>${esc(a)}</p></details>`).join('')}<div class="section split"><div><h2>Local planning guides.</h2><ul>${localGuides.map(g=>`<li><a href="/${slug(g.city)}/${slug(s.name)}/">${esc(s.name)} in ${esc(g.city)}</a></li>`).join('')}</ul></div><div><h2>Related services.</h2>${links(s.related)}</div></div></section>`);
    for (const g of localGuides) {
      const [heading,a,b,sourceIndex]=g.notes[s.name];
      const [label,url]=g.sources[sourceIndex];
      await page(`/${slug(g.city)}/${slug(s.name)}/`,`${s.name} in ${g.city}, TX`,`${s.name} for ${g.city} homes and commercial properties. Plan your project with local guidance from Verde Landscape Services.`,`<section class="wrap section service-page"><p class="breadcrumb"><a href="/services/">Services</a> / <a href="/services/${slug(s.name)}/">${esc(s.name)}</a> / ${esc(g.city)}</p><p class="eyebrow">Serving ${esc(g.city)}, Texas</p><h1>${esc(s.name)} in ${esc(g.city)}.</h1><p>${esc(s.intro)}</p>${button('/contact/','Discuss your property')}<div class="section split"><article><h2>${esc(heading)}.</h2><p>${esc(a)}</p><p>${esc(b)}</p><p>Local reference: <a href="${esc(url)}">${esc(label)}</a>. Confirm requirements for your address and scope with the responsible authority.</p></article><div><h2>Plan your project.</h2>${list(s.scope)}<p><a href="/services/${slug(s.name)}/">Explore ${esc(s.name.toLowerCase())} services and common questions ↗</a></p></div></div><h2>What to share with us.</h2><p>Send the property address, current photographs, any available plans, and your proposed scope. For an occupied commercial property, include access restrictions and scheduling requirements. For a home, identify the areas you want to retain as well as those you want to change.</p><h2>Related services in ${esc(g.city)}.</h2><ul>${s.related.map(n=>`<li><a href="/${slug(g.city)}/${slug(n)}/">${esc(n)}</a></li>`).join('')}</ul><p><a href="/case-studies/">See Verde’s completed projects ↗</a></p></section>`);
    }
  }
}
